### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by Bilka2** [tzwaan/factorio-balancers#1]
I can reproduce a crash with the following input: `balancer-test.py -es --string 0eNqVlWFvgyAQhv/LfaYNnLYqf2VZGm3JQqJogC4zxv8+rFnSdDcGnwziPbx39+It0PV3NVltPMgF9HU0DuTbAk5/mLbf3vl5UiBBezUAA9MO28pNvfZeWVgZaHNTXyDFyv4N87Y1bhqtP3Sq90/BuL4zUMZrr9Uu4LGYL+Y+dOEYKf5iMJhGF8JGs50aUIeSwRwexboJesFgOqaIYIp0DEYwZTpGRDCnZAyPUM7JlJiWKpkSK0ydTIl1qfltV6LNx9OOQAoheLZhBMkRKVpEXAtmuy7cSbhpq6773pmiFtkmpDMsEzLk8QSzjUwryXbyS5mQglYJ6WE8vTr3btDpNTlW4uRfkKcgfppFqkCR0W5aBOYaL1Q1TInHRJFPc4vBp7JuN3hdIdai4VX49hsumURw`

output:
```
{'transport-belt': 15, 'splitter': 7}


^^^^^^^^
SSSSSSSS
 ^<^^>^
  SSSS
   SS
   ^

Testing a 1 - 8 balancer.

  Testing balance.
[K[?25h   -- Output is balanced.#                | 50%
[K[?25h   -- Input is balanced.##############    | 88%
[K[?25hProgress |################################| 100%
  Testing regular throughput.
   -- Full throughput on regular use

  Extensive throughput sweep.
Traceback (most recent call last):
  File "C:\Users\Erik\Documents\GitHub\factorio-balancers\balancer-test\balancer-test.py", line 661, in <module>
    results = balancer.test(balance=args.balance, sweep=args.sweep, extensive_sweep=args.extensive, iterations=args.iterations, verbose=args.verbose)
  File "C:\Users\Erik\Documents\GitHub\factorio-balancers\balancer-test\balancer-test.py", line 602, in test
    for throughput in full_sweep:
TypeError: 'bool' object is not iterable
```

**Comment by tzwaan** [comment]
Thanks for the report.
